CREATE TABLE CAN_MEX_EMPLEADOS (
  ID_EMPLEADO INTEGER,
  ID_DOMICILIO INTEGER,
  ID_CARGO INTEGER,
  NOMBRE VARCHAR2(150),
  FECHA_LLEGADA DATE,
  FECHA_SALIDA DATE,
  
  CONSTRAINT PK_EMPLEADOS PRIMARY KEY (ID_EMPLEADO)
);

DROP TABLE CAN_EMPLEADOS;

SELECT * FROM can_mex_cargos;
SELECT * FROM can_mex_domicilios;
SELECT * FROM can_mex_empleados;
SELECT * FROM can_mex_pagos;
SELECT * FROM can_mex_proveedores;

/*
DROP TABLE CAN_MEX_EMPLEADOS;

ALTER TABLE CAN_MEX_EMPLEADOS DROP COLUMN ID_CARGO;
ALTER TABLE CAN_MEX_EMPLEADOS ADD COLUMN POSICION VARCHAR2(150) AFTER NOMBRE;

SELECT * FROM can_mex_empleados;
*/
CREATE TABLE CAN_MEX_DOMICILIOS (
  ID_DOMICILIO INTEGER,
  DIRECCION VARCHAR2(200),
  
  CONSTRAINT PK_DOMICILIOS PRIMARY KEY (ID_DOMICILIO)
);

SELECT * FROM can_mex_domicilios;

/*
SELECT * FROM can_domicilios;

*/
CREATE TABLE CAN_MEX_CARGOS (
  ID_CARGO INTEGER,
  POSICION VARCHAR2(150),
  
  CONSTRAINT PK_CARGOS PRIMARY KEY (ID_CARGO)
);



CREATE TABLE CAN_MEX_PROVEEDORES (
  ID_PROVEEDOR INTEGER,
  RAZON_SOCIAL VARCHAR2(200),
  
  CONSTRAINT PK_PROVEEDORES PRIMARY KEY (ID_PROVEEDOR)

);

CREATE TABLE CAN_MEX_PAGOS (
  ID_PAGO INTEGER,
  ID_PROVEEDOR INTEGER,
  ID_DOMICILIO INTEGER,
  LINEA_CAPTURA VARCHAR2(100),
  MONTO FLOAT,
  
  CONSTRAINT PK_PAGOS PRIMARY KEY (ID_PAGO),
  CONSTRAINT FK_PROVEEDORES FOREIGN KEY (ID_PROVEEDOR) REFERENCES CAN_MEX_PROVEEDORES(ID_PROVEEDOR),
  CONSTRAINT FK_DOMICILIOS FOREIGN KEY (ID_DOMICILIO) REFERENCES CAN_DOMICILIOS(ID_DOMICILIO)

);

CREATE SEQUENCE SEC_CAN_MEX_EMPLEADOS
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE SEQUENCE SEC_CAN_MEX_DOMICILIOS
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE SEQUENCE SEC_CAN_MEX_CARGOS
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE SEQUENCE SEC_CAN_MEX_PAGOS
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE SEQUENCE SEC_CAN_MEX_PROVEEDORES
START WITH 1
INCREMENT BY 1
NOMAXVALUE;

CREATE OR REPLACE PROCEDURE GUARDAR_CAN_MEX_EMPLEADO(
MY_ID_EMPLEADO OUT INTEGER,
MY_ID_CARGO IN INTEGER,
MY_ID_DOMICILIO IN INTEGER,
MY_NOMBRE IN VARCHAR2,
MY_FECHA_LLEGADA IN DATE,
MY_FECHA_SALIDA IN DATE
)
IS
BEGIN
  SELECT SEC_CAN_MEX_EMPLEADOS.NEXTVAL INTO MY_ID_EMPLEADO FROM DUAL;
  INSERT INTO CAN_MEX_EMPLEADOS VALUES(
    MY_ID_EMPLEADO,
    MY_ID_CARGO,
    MY_ID_DOMICILIO,
    MY_NOMBRE,
    MY_FECHA_LLEGADA,
    MY_FECHA_SALIDA
    );
END;
/

CREATE OR REPLACE PROCEDURE GUARDAR_CAN_MEX_DOMICILIO(
MY_ID_DOMICILIO OUT INTEGER,
MY_DIRECCION IN VARCHAR2
)
IS
BEGIN
  SELECT SEC_CAN_MEX_DOMICILIOS.NEXTVAL INTO MY_ID_DOMICILIO FROM DUAL;
  INSERT INTO CAN_MEX_DOMICILIOS VALUES(
    MY_ID_DOMICILIO,
    MY_DIRECCION
    );
END;
/

CREATE OR REPLACE PROCEDURE GUARDAR_CAN_MEX_CARGO(
MY_POSICION IN VARCHAR2
)
IS
MY_ID_CARGO INTEGER;
BEGIN
  SELECT SEC_CAN_MEX_CARGOS.NEXTVAL INTO MY_ID_CARGO FROM DUAL;
  INSERT INTO CAN_MEX_CARGOS VALUES(
    MY_ID_CARGO,
    MY_POSICION
    );
END;
/

CREATE OR REPLACE PROCEDURE GUARDAR_CAN_MEX_PROVEEDOR(
MY_RAZON_SOCIAL IN VARCHAR2
)
IS
MY_ID_PROVEEDOR INTEGER;
BEGIN
  SELECT SEC_CAN_MEX_PROVEEDORES.NEXTVAL INTO MY_ID_PROVEEDOR FROM DUAL;
  INSERT INTO CAN_MEX_PROVEEDORES VALUES(
    MY_ID_PROVEEDOR,
    MY_RAZON_SOCIAL
    );
END;
/

CREATE OR REPLACE PROCEDURE GUARDAR_CAN_MEX_PAGO(
MY_ID_PAGO OUT INTEGER,
MY_ID_PROVEEDOR IN INTEGER,
MY_ID_DOMICILIO IN INTEGER,
MY_LINEA_CAPTURA IN STRING,
MY_MONTO IN FLOAT
)
IS
BEGIN
  SELECT SEC_CAN_MEX_PAGOS.NEXTVAL INTO MY_ID_PAGO FROM DUAL;
  INSERT INTO CAN_MEX_PAGOS VALUES(
    MY_ID_PAGO,
    MY_ID_PROVEEDOR,
    MY_ID_DOMICILIO,
    MY_LINEA_CAPTURA,
    MY_MONTO
    );
END;
/